# Autogenerated wrapper script for Xorg_libXcomposite_jll for i686-linux-gnu
export libXcomposite

using Xorg_libXfixes_jll
## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `libXcomposite`
const libXcomposite_splitpath = ["lib", "libXcomposite.so"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libXcomposite_path = ""

# libXcomposite-specific global declaration
# This will be filled out by __init__()
libXcomposite_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libXcomposite = "libXcomposite.so.1"


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"Xorg_libXcomposite")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    # From the list of our dependencies, generate a tuple of all the PATH and LIBPATH lists,
    # then append them to our own.
    foreach(p -> append!(PATH_list, p), (Xorg_libXfixes_jll.PATH_list,))
    foreach(p -> append!(LIBPATH_list, p), (Xorg_libXfixes_jll.LIBPATH_list,))

    global libXcomposite_path = normpath(joinpath(artifact_dir, libXcomposite_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libXcomposite_handle = dlopen(libXcomposite_path)
    push!(LIBPATH_list, dirname(libXcomposite_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')

    
end  # __init__()

